const TYPES = {
    FETCH_CREATE_PRODUCT:'FETCH_CREATE_PRODUCT',
    FETCH_PRODUCTS_CREATED:'FETCH_PRODUCTS_CREATED',
    FETCH_MODIFY_PRODUCTS: 'FETCH_MODIFY_PRODUCTS',
    FETCH_DELETE_PRODUCTS:'FETCH_DELETE_PRODUCTS',
    FETCH_ERROR:'FETCH_ERROR'
}

export default TYPES;